#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : vapoursynth
Version  : r69
Release  : 1
URL      : https://github.com/vapoursynth/vapoursynth/archive/R69/vapoursynth-R69.tar.gz
Source0  : https://github.com/vapoursynth/vapoursynth/archive/R69/vapoursynth-R69.tar.gz
Summary  : A frameserver for the 21st century
Group    : Development/Tools
License  : LGPL-2.1
Requires: vapoursynth-bin = %{version}-%{release}
Requires: vapoursynth-lib = %{version}-%{release}
Requires: vapoursynth-license = %{version}-%{release}
Requires: vapoursynth-python = %{version}-%{release}
Requires: vapoursynth-python3 = %{version}-%{release}
BuildRequires : file
BuildRequires : pkgconfig(zimg)
BuildRequires : pypi-cython
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: vapoursynth-version-info.patch

%description
# vapoursynth
[![Windows](https://github.com/vapoursynth/vapoursynth/actions/workflows/windows.yml/badge.svg)](https://github.com/vapoursynth/vapoursynth/actions/workflows/windows.yml)
[![Linux](https://github.com/vapoursynth/vapoursynth/actions/workflows/linux.yml/badge.svg)](https://github.com/vapoursynth/vapoursynth/actions/workflows/linux.yml)
[![macOS](https://github.com/vapoursynth/vapoursynth/actions/workflows/macos.yml/badge.svg)](https://github.com/vapoursynth/vapoursynth/actions/workflows/macos.yml)
[![codespell](https://github.com/vapoursynth/vapoursynth/actions/workflows/codespell.yml/badge.svg)](https://github.com/vapoursynth/vapoursynth/actions/workflows/codespell.yml)

%package bin
Summary: bin components for the vapoursynth package.
Group: Binaries
Requires: vapoursynth-license = %{version}-%{release}

%description bin
bin components for the vapoursynth package.


%package dev
Summary: dev components for the vapoursynth package.
Group: Development
Requires: vapoursynth-lib = %{version}-%{release}
Requires: vapoursynth-bin = %{version}-%{release}
Provides: vapoursynth-devel = %{version}-%{release}
Requires: vapoursynth = %{version}-%{release}

%description dev
dev components for the vapoursynth package.


%package lib
Summary: lib components for the vapoursynth package.
Group: Libraries
Requires: vapoursynth-license = %{version}-%{release}

%description lib
lib components for the vapoursynth package.


%package license
Summary: license components for the vapoursynth package.
Group: Default

%description license
license components for the vapoursynth package.


%package python
Summary: python components for the vapoursynth package.
Group: Default
Requires: vapoursynth-python3 = %{version}-%{release}

%description python
python components for the vapoursynth package.


%package python3
Summary: python3 components for the vapoursynth package.
Group: Default
Requires: python3-core

%description python3
python3 components for the vapoursynth package.


%prep
%setup -q -n vapoursynth-R69
cd %{_builddir}/vapoursynth-R69
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724774784
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --enable-x86-asm \
--enable-core \
--enable-vsscript \
--enable-vspipe \
--enable-python-module
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724774784
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vapoursynth
cp %{_builddir}/vapoursynth-R69/COPYING.LESSER %{buildroot}/usr/share/package-licenses/vapoursynth/37d2f1d62fec4da0caf06e5da21afc3521b597aa || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/vspipe

%files dev
%defattr(-,root,root,-)
/usr/include/vapoursynth/VSConstants4.h
/usr/include/vapoursynth/VSHelper.h
/usr/include/vapoursynth/VSHelper4.h
/usr/include/vapoursynth/VSScript.h
/usr/include/vapoursynth/VSScript4.h
/usr/include/vapoursynth/VapourSynth.h
/usr/include/vapoursynth/VapourSynth4.h
/usr/lib64/libvapoursynth-script.so
/usr/lib64/libvapoursynth.so
/usr/lib64/pkgconfig/vapoursynth-script.pc
/usr/lib64/pkgconfig/vapoursynth.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvapoursynth-script.so.0
/usr/lib64/libvapoursynth-script.so.0.0.0
/usr/lib64/libvapoursynth.so.69
/usr/lib64/libvapoursynth.so.69.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vapoursynth/37d2f1d62fec4da0caf06e5da21afc3521b597aa

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
